name: Automated tests inference

on:
  push:
    paths:
      - '**.jpg'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        python -m pytest

    - uses: actions/checkout@main
    - name: Make inference
      shell: bash
      env:
        aws_key_id: ${{secrets.AWSACCESSKEYID}}
        aws_secret_access_key: ${{secrets.AWSSECRETKEY}}

      run: |
        sudo apt-get update && sudo apt-get -y install awscli
        aws configure set aws_access_key_id $aws_key_id
        aws configure set aws_secret_access_key $aws_secret_access_key
        aws configure set default.region eu-west-1
        python -m app.main(aws_access_key_id, aws_secret_access_key)
